language: node_js
node_js:
- '4'
deploy:
  provider: npm
  email: mail@jojow.de
  api_key:
    secure: dE69UJ5vSYgf5vo8ADllAMvwDkaFuTznRTSd9qEIb5/JuTFLX51BQM8srk0RA+rkO/yzzEthDD3Zcj6OI68yH/pwsJfxQjgK/kYttWckl4QE4By9iXFEXFXJcuMklVcOQJhH7QwsriQ/KxH4K7k4eAjcJd22WM6Z5y9qiZBd/7c=
